CREATE TYPE "ProposalKind" AS ENUM ('MESSAGE_REPLY', 'DOCUMENT_REVIEW');

ALTER TABLE "proposals"
ADD COLUMN "kind" "ProposalKind" NOT NULL DEFAULT 'MESSAGE_REPLY',
ADD COLUMN "sourceMessageIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];